//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TimeManager.Launcher.Core
{
    using System;
    using System.Collections.Generic;
    
    public partial class Project
    {
        public Project()
        {
            this.Versions = new HashSet<Version>();
        }
    
        public System.Guid Project_Id { get; set; }
        public string Project_Name { get; set; }
        public string Project_Description { get; set; }
    
        public virtual ICollection<Version> Versions { get; set; }
    }
}
