//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TimeManager.Launcher.SilentMode.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProjectItems
    {
        public ProjectItems()
        {
            this.Version = new HashSet<Version>();
        }
    
        public System.Guid ProjectItems_Id { get; set; }
        public string ProjectItems_FileName { get; set; }
        public string ProjectItems_Extension { get; set; }
        public Nullable<bool> ProjectItems_IsStarted { get; set; }
        public string ProjectItems_MD5 { get; set; }
        public string ProjectItems_Description { get; set; }
        public Nullable<bool> ProjectItems_IsCustomeSettings { get; set; }
        public string ProjectItems_PathToFile { get; set; }
        public string ProjectItems_MaskPathToFile { get; set; }
    
        public virtual ICollection<Version> Version { get; set; }
    }
}
