//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TimeManager.Launcher.SilentMode.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Version
    {
        public Version()
        {
            this.ProjectItems = new HashSet<ProjectItems>();
        }
    
        public System.Guid Version_Id { get; set; }
        public string Version_Name { get; set; }
        public string Version_Description { get; set; }
        public Nullable<System.Guid> Project_Id { get; set; }
        public Nullable<bool> Version_IsCurrentVersion { get; set; }
    
        public virtual Project Project { get; set; }
        public virtual ICollection<ProjectItems> ProjectItems { get; set; }
    }
}
